Revert to "FRRouting Release 6.0" commit
Revert to the commit c8c24278b1d1da271089a36303bb7708568ce231.
Because the latest branch stable/6.0 has some compile problems about
debian package, so to revert to the FRR 6.0 Release version, refer:
https://github.com/FRRouting/frr/releases/tag/frr-6.0 .

diff --git a/redhat/frr.init b/redhat/frr.init
--- a/redhat/frr.init
+++ b/redhat/frr.init
@@ -107,28 +107,22 @@ check_daemon()
 # The Frr daemons creates the pidfile when starting.
 start()
 {
-    local dmn inst
-    dmn="$1"
-    inst="$2"
-
     ulimit -n $MAX_FDS > /dev/null 2> /dev/null
-    if [ "$dmn" = "watchfrr" ]; then
+    if [ "$1" = "watchfrr" ]; then
 
         # We may need to restart watchfrr if new daemons are added and/or
         # removed
-        if started "$dmn" ; then
+        if started "$1" ; then
             stop watchfrr
         else
             # Echo only once. watchfrr is printed in the stop above
-            echo -n " $dmn"
+            echo -n " $1"
         fi
 
         if [ -e /var/run/frr/watchfrr.started ] ; then
             rm /var/run/frr/watchfrr.started
         fi
-        # redhat /etc/init.d/functions daemon() re-expands args :(
-        # eval "set - $watchfrr_options"
-        daemon --pidfile=`pidfile $dmn` "$D_PATH/$dmn" -d "$watchfrr_options"
+        daemon --pidfile=`pidfile $1` "$D_PATH/$1" -d "${watchfrr_options[@]}"
         RETVAL=$?
         [ $RETVAL -ne 0 ] && break
         for i in `seq 1 10`;
@@ -141,25 +135,25 @@ start()
             fi
         done
         RETVAL=1
-    elif [ -n "$inst" ]; then
-        echo -n " $dmn-$inst"
-        if ! check_daemon $dmn $inst ; then
+    elif [ -n "$2" ]; then
+        echo -n " $1-$2"
+        if ! check_daemon $1 $2 ; then
             echo -n " (binary does not exist)"
             return;
         fi
-        daemon --pidfile=`pidfile $dmn-$inst` "$D_PATH/$dmn" -d `eval echo "$""$dmn""_options"` -n "$inst"
+        daemon --pidfile=`pidfile $1-$2` "$D_PATH/$1" -d `eval echo "$""$1""_options"` -n "$2"
         RETVAL=$?
     else
-        echo -n " $dmn "
-        if ! check_daemon $dmn; then
+        echo -n " $1 "
+        if ! check_daemon $1; then
             echo " (binary does not exist)"
             return;
         fi
-        daemon --pidfile=`pidfile $dmn` "$D_PATH/$dmn" -d `eval echo "$""$dmn""_options"`
+        daemon --pidfile=`pidfile $1` "$D_PATH/$1" -d `eval echo "$""$1""_options"`
         RETVAL=$?
     fi
     echo
-    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$dmn
+    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$1
     return $RETVAL
 }
 
@@ -229,9 +223,11 @@ start_watchfrr()
     fi
 
     # Check variable type
-    if declare -p watchfrr_options | grep -q '^declare \-a'; then
-        # old array support
-        watchfrr_options="${watchfrr_options[@]}"
+    if ! declare -p watchfrr_options | grep -q '^declare \-a'; then
+        echo
+        echo "ERROR: The variable watchfrr_options from /etc/frr/daemons must be a BASH array!"
+        echo "ERROR: Please convert config file and restart!"
+        exit 1
     fi
 
     # Which daemons have been started?
@@ -245,13 +241,13 @@ start_watchfrr()
                     eval "inst_disable=\${${daemon_name}_${inst}}"
                     if [ -z ${inst_disable} ] || [ ${inst_disable} != 0 ]; then
                         if check_daemon $daemon_name $inst; then
-                            watchfrr_options="$watchfrr_options ${daemon_name}-${inst}"
+                            watchfrr_options+=("${daemon_name}-${inst}")
                         fi
                     fi
                 done
             else
                 if check_daemon $daemon_name; then
-                    watchfrr_options="$watchfrr_options $daemon_name"
+                    watchfrr_options+=($daemon_name)
                 fi
             fi
             found_one=1
